// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://4z7xwfkgmbaa3cmpxeldzcs2we.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fj55qwenk5ayfk5mpwqguvb43i",
    "aws_content_delivery_bucket": "videoapp-20181214122915-hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://videoapp-20181214122915-hostingbucket.s3-website-us-west-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-west-2:d4105374-d598-4bdb-ad64-ca741fbd3762",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pLByRXLNW",
    "aws_user_pools_web_client_id": "663ivcu64hvqgmsaibb37qio38",
    "aws_user_files_s3_bucket": "videoapp48fd6c13148743308abc16fa334eb464",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
